services:
  corretto:
    build:
      context: ./app
      dockerfile: Dockerfile_corretto
    ports:
      - "8081:8080"

  distroless:
    build:
      context: ./app
      dockerfile: Dockerfile_distroless
    ports:
      - "8082:8080"

  distroless-custom-jre:
    build:
      context: ./app
      dockerfile: Dockerfile_distroless_custom_jre
    ports:
      - "8083:8080"

  distroless-custom-jre-buildpack:
    image: distroless-jvm-examples-distroless-custom-jre-buildpack
    ports:
      - "8084:8080"

  notebook:
    profiles: ["notebook"]
    image: jupyter/datascience-notebook:latest
    command:
      - "start-notebook.sh"
      - "--NotebookApp.token=''"
      - "--NotebookApp.disable_check_xsrf=True"
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/home/jovyan
