[tools]
aws = { version = "2.34.51", symlink_bins = "true" }
dive = "0.13.1"
gradle = "9.5.1"
java = "corretto-25.0.3.9.1"
terraform = "1.15.4"

[env]
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""

[tasks.jdeps]
description = "Show module dependencies of jar"
run = """
gradle clean app:build -x test

readonly TMP_DIR="/tmp/app-jar"
mkdir -p ${TMP_DIR}
trap 'rm -rf ${TMP_DIR}' EXIT

unzip -q app/build/libs/app.jar -d "${TMP_DIR}"

jdeps \
  -classpath '${TMP_DIR}/BOOT-INF/lib/*:${TMP_DIR}/BOOT-INF/classes:${TMP_DIR}' \
  --print-module-deps \
  --ignore-missing-deps \
  --module-path ${TMP_DIR}/BOOT-INF/lib/javax.activation-api-1.2.0.jar \
  --recursive \
  --multi-release 25 \
  -quiet \
  ${TMP_DIR}/org ${TMP_DIR}/BOOT-INF/classes ${TMP_DIR}/BOOT-INF/lib/*.jar
"""

[tasks.ecr-login]
run = """
aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 451348341937.dkr.ecr.ap-northeast-1.amazonaws.com
"""

[tasks.push-image]
depends = ["ecr-login"]
run = """
gradle clean bootBuildImage
docker compose build
docker tag distroless-jvm-examples-corretto:latest 451348341937.dkr.ecr.ap-northeast-1.amazonaws.com/distroless-jvm-samples-app:corretto
docker push 451348341937.dkr.ecr.ap-northeast-1.amazonaws.com/distroless-jvm-samples-app:corretto
"""
