# syntax=docker/dockerfile:1

FROM amazoncorretto:25.0.3-al2023 AS build
WORKDIR /jlink
RUN jlink \
    --verbose \
    --compress=2 \
    --strip-java-debug-attributes \
    --no-header-files \
    --no-man-pages \
    --add-modules java.base,java.compiler,java.desktop,java.instrument,java.naming,java.net.http,java.prefs,java.scripting,java.security.jgss,java.sql,jdk.jfr,jdk.management,jdk.unsupported \
    --output jre-min

FROM gcr.io/distroless/java-base-debian13:nonroot
WORKDIR /deployments
COPY --from=build --chown=nonroot:nonroot /jlink/jre-min /opt/jre-min
ENV JAVA_HOME=/opt/jre-min
ENV PATH=$JAVA_HOME/bin:$PATH
ARG JAR_FILE=build/libs/app.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
